{
 "title": "Personal",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Current Weather Conditions: Beford",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"open_weather_map\" and r.name == \"Bedford\")\n  |> filter(fn: (r) => r[\"_field\"] == \"main_temp\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "main_temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"open_weather_map\" and r.name == \"Bedford\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_speed\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "wind_speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"open_weather_map\" and r.name == \"Bedford\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wind_deg\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "wind_deg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"open_weather_map\" and r.name == \"Bedford\")\n  |> filter(fn: (r) => r[\"_field\"] == \"main_pressure\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "main_pressure" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Weather condition",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "openweathermap",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"open_weather_map\" and r.name == \"Bedford\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weather_0_description\")\n  |> yield(name: \"last\")\n",
     "select": [
      [
       { "params": [ "weather_0_description" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Sunrise time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"open_weather_map\" and r.name == \"Bedford\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sys_sunrise\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "sys_sunrise" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"open_weather_map\" and r.name == \"Bedford\")\n  |> filter(fn: (r) => r[\"_field\"] == \"clouds_all\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "clouds_all" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"open_weather_map\" and r.name == \"Bedford\")\n  |> filter(fn: (r) => r[\"_field\"] == \"main_humidity\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "main_humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Sunset time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openweathermap",
     "query": "from(bucket: \"telegraf\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"open_weather_map\" and r.name == \"Bedford\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sys_sunset\")\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "sys_sunset" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sys_country", "operator": "=~", "value": "/^$country$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$city$/" }
     ]
    }
   ]
  },
  {
   "title": "Weight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "masslb" } },
   "targets": [
    {
     "query": "from(bucket: \"fitness\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weight\")\n  |> map(fn: (r) => ({r with _value: (float(v: r._value) * .00220462) } ))\n  |> group(columns: [\"_field\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  {
   "title": "Sleep",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "from(bucket: \"fitness\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sleepingSeconds\")\n  |> group(columns: [\"_field\"])\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")"
    }
   ]
  },
  { "title": "Fitness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 }, "options": { "content": "# Monthly Summary" } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    { "activityStat": "moving_time" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "activityStat": "distance" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "activityStat": "moving_time" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "activityStat": "total_elevation_gain" }
   ]
  },
  {
   "title": "Activities",
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 0, "y": 22 },
   "targets": [
    { "activityStat": "distance" }
   ]
  },
  {
   "title": "Indoor Biking",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "import \"date\"\n\nyear = date.year(t: now())\n\ncdate = \"${year}-01-01T00:00:00.000000000Z\"\n\nts = time(v: cdate)\n\ntype = from(bucket: \"fitness\")\n    |> range(start: ts)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"activityType_typeKey\" and r._value == \"indoor_cycling\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\ndistance = from(bucket: \"fitness\")\n    |> range(start: ts)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"distance\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\njoin(\n    tables: {activity:type, distance:distance},\n    on: [\"_time\"],\n)\n  |> keep(columns: [\"_time\", \"distance\"])\n"
    }
   ]
  },
  {
   "title": "Road Biking",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "query": "import \"date\"\n\nyear = date.year(t: now())\n\ncdate = \"${year}-01-01T00:00:00.000000000Z\"\n\nts = time(v: cdate)\n\ntype = from(bucket: \"fitness\")\n    |> range(start: ts)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"activityType_typeKey\" and r._value == \"road_biking\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\ndistance = from(bucket: \"fitness\")\n    |> range(start: ts)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"distance\")\n    |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n\njoin(\n    tables: {activity:type, distance:distance},\n    on: [\"_time\"],\n)\n  |> keep(columns: [\"_time\", \"distance\"])\n"
    }
   ]
  },
  {
   "title": "Step Goal vs Actual",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "query": "from(bucket: \"fitness\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"totalSteps\" or r[\"_measurement\"] == \"dailyStepGoal\")\n  |> group()\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  "
    }
   ]
  }
 ]
}